os:
  - linux
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "node"

script:
  - npm test

after_success:
  - npm install coveralls
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
